### ISSUE TITLE
gleam_stdlib v0.18.1 fails to compile with mix_gleam v0.2

### ISSUE THREAD

**Issue by srikanthkyatham** [gleam-lang/mix_gleam#9]
Hi 

gleam_stdlib v0.18.1 fails to compile with mix_gleam v0.2, but the following combination works
gleam_stdlib v0.17.1 fails to compile with mix_gleam v0.2

the compilation error which is thrown is 

Could not compile :gleam_stdlib, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
Unchecked dependencies for environment dev:
* gleam_stdlib (Hex package)
  could not find an app file at "_build/dev/lib/gleam_stdlib/ebin/gleam_stdlib.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies

**Comment by lpil** [comment]
Hi @srikanthkyatham ! v0.2 doesn't support packages that use the Gleam build tool. Could you upgrade to v0.3? Thanks.

**Comment by srikanthkyatham** [comment]
Hi @lpil 

That was fast. I confirm that the changes are working. Followed the instructions

**Comment by lpil** [comment]
Good to hear!

**Comment by srikanthkyatham** [comment]
> Good to hear!

Good work
